### PR TITLE
Update 0000-router-dynamic-routing.md

### PR DESCRIPTION
**Pull request by smolinari**
Just some grammatical corrections. Hope you don't mind.

Scott

### CODE REVIEW

**Review by posva — APPROVED** [review]
Cool, thanks! I think I need to learn about breaks with `,`. I keep missing them between logical connectors in sentences

**Comment by smolinari** [comment]
It's easy (and sometimes I get carried away with commas myself), but if there is a conjugation of two clauses, you can always use a comma. They should definitely be used, if the conjugated clause can be a sentence on its own. (like "You can always use a comma." above.) 😁 

And sometimes, you can break them up in different sentences too. 

Scott

**Comment by posva** [comment]
I see, thanks! I still need to document myself a bit more because I wouldn't have used a comma in _They should definitely be used, if the conjugated..._. I would have use a dot to break instead. But I wonder if that one was optional

**Comment by smolinari** [comment]
Do you mean, 

 They should definitely be used. If the conjugated clause can be a sentence on its own. 

??? 

That would be incorrect. 😃 

My first sentence could have been broken up. 

It's easy (and sometimes I get carried away with commas myself). But, if there is a conjugation of two clauses, you can always use a comma.

Scott

**Comment by posva** [comment]
Right, that second sentence starting with _If_ doesn't make sense on itself. I realize I removed a part I wanted to say: I would have not included any comma at all instead. What I wanted to say is that I would have rather used a stop (I see now it doesn't make sense though)

**Comment by smolinari** [comment]
No worries. Your English is pretty darn good, because the important thing is to get the point across, and you seem to be able to do that well. (more examples there of conjugation with a comma :grin:)

Scott

**Comment by posva** [comment]
Thank you 🙂 
Yeah, I also feel like I usually get my point across 😆. Since I use English everyday way more than Spanish and French, I get a good opportunity to keep learning and I want to take it! Thanks for the lesson haha

**Comment by smolinari** [comment]
> I get a good opportunity to keep learning and I want to take it! 

It was optional, but more proper with a comma, because the last clause could be a sentence on its own. 😁 Keep up the good work and I'll shut up now. 😁 

I get a good opportunity to keep learning, and I want to take it! 

Scott

**Pull request merged**
