### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by posva** [comment]
Thanks but the current version is correct

**Comment by ghost** [comment]
Doesnt feel like it but anyways.

**Comment by ghost** [comment]
@posva Actually i am sure that you are wrong. There are some special situation normal rules doesn't apply because of pronunciation. ForEx:
An hour.
A usecase.

**Comment by posva** [comment]
For some reason I thought the PR introduced `an usecase` to replace `a usecase` and not the other way around 🤦‍♂️
Thanks!

**Pull request merged**
